name: Static code analysis

on: [push, pull_request]

jobs:
  staticAnalysis:
    name: Psalm and PHPStan static analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpstan, psalm

      - name: Run Psalm
        run: psalm --show-info=true

      - name: Run PHPStan
        run: phpstan analyse src --level 9