name: Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
          composer_ignore_platform_reqs: true

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga:0.12.48
        env:
          REQUIRE_DEV: true
        with:
          entrypoint: /composer/vendor/bin/phpstan
          args: analyze --no-progress --level 9
